name: Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Truffle compile
        run: npm run truffle:compile
      - name: Typechain generate
        run: npm run typechain:generate
      - name: Build Next.js App
        run: npm run next:build