name: Linter and Prettier

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Linter and Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm  install
      - name: Prettier
        run: npm run prettier
      - name: Lint
        run: npm run lint